// Generated by scripts/update-market-sources.mjs on 2026-08-27.
export type BrokerReport = { title: string; broker: string; date: string; url: string; pdfUrl: string };
export type StockNews = { title: string; office: string; date: string; url: string };
export type MarketSourceRecord = { company: string; code: string; updatedAt: string; report: BrokerReport | null; reportListUrl: string; news: StockNews | null; newsListUrl: string; error?: string };

export const marketSourcesByStock: Record<string, MarketSourceRecord> = {
  "가온전선": {
    "company": "가온전선",
    "code": "000500",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=000500",
    "news": {
      "title": "대신證 \"가온전선, AI 데이터센터 전력 수요 성장 초기\"…목표가 36만...",
      "office": "뉴스1",
      "date": "20260930",
      "url": "https://n.news.naver.com/mnews/article/421/0009199582"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/000500/news"
  },
  "가온칩스": {
    "company": "가온칩스",
    "code": "399720",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=399720",
    "news": {
      "title": "[오늘장 탑픽] 삼성 파운드리 흑자 전환…가온칩스·에이직랜드 주목",
      "office": "SBS Biz",
      "date": "20260715",
      "url": "https://n.news.naver.com/mnews/article/374/0000521782"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/399720/news"
  },
  "고영": {
    "company": "고영",
    "code": "098460",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=098460",
    "news": {
      "title": "고영 '소캠2' 검사장비 추가 수주…국내 메모리 제조사 공급",
      "office": "전자신문",
      "date": "20260930",
      "url": "https://n.news.naver.com/mnews/article/030/0003471121"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/098460/news"
  },
  "네패스아크": {
    "company": "네패스아크",
    "code": "330860",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=330860",
    "news": {
      "title": "네패스아크, 반도체 테스트 설비에 667억 투자 결정",
      "office": "블로터",
      "date": "20260526",
      "url": "https://n.news.naver.com/mnews/article/293/0000085285"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/330860/news"
  },
  "뉴로메카": {
    "company": "뉴로메카",
    "code": "348340",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=348340",
    "news": {
      "title": "뉴로메카, 카이스트와 '단일 카메라 기반 정밀 작업 로봇 AI' 개발",
      "office": "이데일리",
      "date": "20261002",
      "url": "https://n.news.naver.com/mnews/article/018/0006379375"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/348340/news"
  },
  "대덕전자": {
    "company": "대덕전자",
    "code": "353200",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=353200",
    "news": {
      "title": "“대덕전자, 실적 기반 경쟁사 주가 캐치업…목표가 19만원 상향”-iM",
      "office": "이데일리",
      "date": "20260928",
      "url": "https://n.news.naver.com/mnews/article/018/0006376115"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/353200/news"
  },
  "대주전자재료": {
    "company": "대주전자재료",
    "code": "078600",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=078600",
    "news": {
      "title": "대주전자재료, 북미 우주항공기업 협력 확대…음극재·CNT 샘플 공급",
      "office": "이데일리",
      "date": "20260821",
      "url": "https://n.news.naver.com/mnews/article/018/0006355415"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/078600/news"
  },
  "대한전선": {
    "company": "대한전선",
    "code": "001440",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=001440",
    "news": {
      "title": "호반 계열 대한전선, 82년생 '김준석 대표' 체제로 세대교체…\"글로벌...",
      "office": "뉴시스",
      "date": "20261007",
      "url": "https://n.news.naver.com/mnews/article/003/0014237437"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/001440/news"
  },
  "더블유씨피": {
    "company": "더블유씨피",
    "code": "393890",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=393890",
    "news": {
      "title": "두산·세아베스틸지주·더블유씨피[하나證 주간추천주]",
      "office": "이데일리",
      "date": "20260919",
      "url": "https://n.news.naver.com/mnews/article/018/0006372370"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/393890/news"
  },
  "동진쎄미켐": {
    "company": "동진쎄미켐",
    "code": "005290",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=005290",
    "news": {
      "title": "[AI 대전환 리딩 전략]동진쎄미켐, AI 반도체 공급망 핵심 주자로",
      "office": "블로터",
      "date": "20260924",
      "url": "https://n.news.naver.com/mnews/article/293/0000090884"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/005290/news"
  },
  "두산로보틱스": {
    "company": "두산로보틱스",
    "code": "454910",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=454910",
    "news": {
      "title": "두산로보틱스 \"로봇 데이터는 고작 1년…현장서 격차 메운다\"",
      "office": "지디넷코리아",
      "date": "20261007",
      "url": "https://n.news.naver.com/mnews/article/092/0002440137"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/454910/news"
  },
  "두산에너빌리티": {
    "company": "두산에너빌리티",
    "code": "034020",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=034020",
    "news": {
      "title": "두산에너빌리티, 美가스터빈 공급망 진입 본격화…대미 투자 1호 참여...",
      "office": "뉴시스",
      "date": "20261007",
      "url": "https://n.news.naver.com/mnews/article/003/0014239409"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/034020/news"
  },
  "두산테스나": {
    "company": "두산테스나",
    "code": "131970",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=131970",
    "news": {
      "title": "“테슬라 AI5 수주 가시화” 두산테스나, 2027년 영업이익 220% 증가 전...",
      "office": "주간동아",
      "date": "20261006",
      "url": "https://n.news.naver.com/mnews/article/037/0000038936"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/131970/news"
  },
  "디앤디파마텍": {
    "company": "디앤디파마텍",
    "code": "347850",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=347850",
    "news": {
      "title": "디앤디파마텍 \"MASH 치료제, 美 학회 결과 발표\"",
      "office": "아이뉴스24",
      "date": "20261006",
      "url": "https://n.news.naver.com/mnews/article/031/0001063844"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/347850/news"
  },
  "레인보우로보틱스": {
    "company": "레인보우로보틱스",
    "code": "277810",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=277810",
    "news": {
      "title": "삼성전자 100조 실적에도…코스피 약보합 출발 [시황]",
      "office": "데일리안",
      "date": "20261008",
      "url": "https://n.news.naver.com/mnews/article/119/0003140727"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/277810/news"
  },
  "로보스타": {
    "company": "로보스타",
    "code": "090360",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=090360",
    "news": {
      "title": "인구 대국 가고 '로봇 대국' 온다?… AI가 예측한 국력의 새 방정식",
      "office": "지디넷코리아",
      "date": "20260916",
      "url": "https://n.news.naver.com/mnews/article/092/0002437642"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/090360/news"
  },
  "로보티즈": {
    "company": "로보티즈",
    "code": "108490",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=108490",
    "news": {
      "title": "투모로로보틱스, 로봇 조작 파운데이션 모델 공개",
      "office": "디지털데일리",
      "date": "20261007",
      "url": "https://n.news.naver.com/mnews/article/138/0002243996"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/108490/news"
  },
  "리가켐바이오": {
    "company": "리가켐바이오",
    "code": "141080",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=141080",
    "news": {
      "title": "삼성바이오·롯데바이오, ‘바이오 재팬’ 출격…K-바이오 수주 영토...",
      "office": "헤럴드경제",
      "date": "20261002",
      "url": "https://n.news.naver.com/mnews/article/016/0002704672"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/141080/news"
  },
  "미래컴퍼니": {
    "company": "미래컴퍼니",
    "code": "049950",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=049950",
    "news": {
      "title": "[인터뷰] 김준구 미래컴퍼니 대표 “외산 독점 깨고 수술 로봇 국산화...",
      "office": "조선비즈",
      "date": "20260903",
      "url": "https://n.news.naver.com/mnews/article/366/0001190048"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/049950/news"
  },
  "바이오니아": {
    "company": "바이오니아",
    "code": "064550",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=064550",
    "news": {
      "title": "바이오니아 \"박한오 회장 콘코디아서밋 참석…팬데믹 대응방안 논의\"",
      "office": "머니투데이",
      "date": "20260928",
      "url": "https://n.news.naver.com/mnews/article/008/0005418826"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/064550/news"
  },
  "비에이치아이": {
    "company": "비에이치아이",
    "code": "083650",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=083650",
    "news": {
      "title": "비에이치아이, 2169.9억 규모 공급계약 체결",
      "office": "이데일리",
      "date": "20260916",
      "url": "https://n.news.naver.com/mnews/article/018/0006370424"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/083650/news"
  },
  "비츠로테크": {
    "company": "비츠로테크",
    "code": "042370",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=042370",
    "news": {
      "title": "271조 대미 투자 청사진에 원전주 ‘들썩’…원일티엔아이 상한가 [이...",
      "office": "서울경제",
      "date": "20261002",
      "url": "https://n.news.naver.com/mnews/article/011/0004667573"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/042370/news"
  },
  "산일전기": {
    "company": "산일전기",
    "code": "062040",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=062040",
    "news": {
      "title": "산일전기, 350억원 규모 미국 BESS 변압기 공급 [공시]",
      "office": "파이낸셜뉴스",
      "date": "20261006",
      "url": "https://n.news.naver.com/mnews/article/014/0005585568"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/062040/news"
  },
  "삼성바이오로직스": {
    "company": "삼성바이오로직스",
    "code": "207940",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=207940",
    "news": {
      "title": "[기자의눈] 삼성바이오로직스, 노사갈등에 멍드는 기업가치",
      "office": "서울경제",
      "date": "20261008",
      "url": "https://n.news.naver.com/mnews/article/011/0004669270"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/207940/news"
  },
  "삼성전기": {
    "company": "삼성전기",
    "code": "009150",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=009150",
    "news": {
      "title": "\"목표가 230만원\" 삼성전기, 지금 주목해야 할 이유 다섯",
      "office": "이데일리",
      "date": "20261008",
      "url": "https://n.news.naver.com/mnews/article/018/0006383290"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/009150/news"
  },
  "삼성전자": {
    "company": "삼성전자",
    "code": "005930",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=005930",
    "news": {
      "title": "삼성전자 100조 실적에도…코스피 약보합 출발 [시황]",
      "office": "데일리안",
      "date": "20261008",
      "url": "https://n.news.naver.com/mnews/article/119/0003140727"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/005930/news"
  },
  "삼성SDI": {
    "company": "삼성SDI",
    "code": "006400",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=006400",
    "news": {
      "title": "\"삼성SDI, 실적 개선 이어질 것...수주 기대에 목표가 상향\"",
      "office": "파이낸셜뉴스",
      "date": "20261008",
      "url": "https://n.news.naver.com/mnews/article/014/0005586545"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/006400/news"
  },
  "삼현": {
    "company": "삼현",
    "code": "437730",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=437730",
    "news": {
      "title": "“성능 산포 줄여 양산 경쟁력”…삼현, 휴머노이드 액추에이터 성장...",
      "office": "이데일리",
      "date": "20260907",
      "url": "https://n.news.naver.com/mnews/article/018/0006365081"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/437730/news"
  },
  "새빗켐": {
    "company": "새빗켐",
    "code": "107600",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=107600",
    "news": {
      "title": "'안정된 캐시카우·신사업'…새빗켐, 투트랙 전략으로 실적 반등 노려",
      "office": "동행미디어 시대",
      "date": "20260130",
      "url": "https://n.news.naver.com/mnews/article/417/0001127477"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/107600/news"
  },
  "서진시스템": {
    "company": "서진시스템",
    "code": "178320",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=178320",
    "news": {
      "title": "서진시스템, 베트남 비핵심 사업 중단…ESS·반도체장비 핵심사업에 ...",
      "office": "이데일리",
      "date": "20260930",
      "url": "https://n.news.naver.com/mnews/article/018/0006377921"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/178320/news"
  },
  "성일하이텍": {
    "company": "성일하이텍",
    "code": "365340",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=365340",
    "news": {
      "title": "디알티, 이차전지 재활용 고효율 BM 양산설비 본격 가동",
      "office": "조선비즈",
      "date": "20260909",
      "url": "https://n.news.naver.com/mnews/article/366/0001191218"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/365340/news"
  },
  "셀트리온": {
    "company": "셀트리온",
    "code": "068270",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=068270",
    "news": {
      "title": "셀트리온 ‘앱토즈마’, 미국서 소아 코로나19 적응증 승인",
      "office": "디지털타임스",
      "date": "20261007",
      "url": "https://n.news.naver.com/mnews/article/029/0003052012"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/068270/news"
  },
  "솔브레인": {
    "company": "솔브레인",
    "code": "357780",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=357780",
    "news": {
      "title": "\"AI 메모리 증설에 공정 실적 쌓였다\"…솔브레인, 호실적 배경 [실적w...",
      "office": "뉴스1",
      "date": "20260923",
      "url": "https://n.news.naver.com/mnews/article/421/0009187741"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/357780/news"
  },
  "신성에스티": {
    "company": "신성에스티",
    "code": "416180",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=416180",
    "news": {
      "title": "신성에스티, 북미 ESS 양산 확대 본격화",
      "office": "아시아경제",
      "date": "20260903",
      "url": "https://n.news.naver.com/mnews/article/277/0005811172"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/416180/news"
  },
  "심텍": {
    "company": "심텍",
    "code": "222800",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=222800",
    "news": {
      "title": "\"반도체 기판 가격 또 오른다…대덕전자·심텍 등 수천억 투자\"-하나",
      "office": "한국경제",
      "date": "20261008",
      "url": "https://n.news.naver.com/mnews/article/015/0005340376"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/222800/news"
  },
  "쎄트렉아이": {
    "company": "쎄트렉아이",
    "code": "099320",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=099320",
    "news": {
      "title": "누리호 5차 발사 성공…‘네온샛’과 ‘대전샛’은 어떤 위성?",
      "office": "KBS",
      "date": "20261008",
      "url": "https://n.news.naver.com/mnews/article/056/0012269920"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/099320/news"
  },
  "씨메스": {
    "company": "씨메스",
    "code": "475400",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=475400",
    "news": {
      "title": "씨메스로보틱스, 상반기 매출 95.2억…역대 최대",
      "office": "이데일리",
      "date": "20260813",
      "url": "https://n.news.naver.com/mnews/article/018/0006351003"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/475400/news"
  },
  "씨아이에스": {
    "company": "씨아이에스",
    "code": "222080",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=222080",
    "news": {
      "title": "쿠팡 홀린 SFA 물류로봇, 휴머노이드 진화",
      "office": "한국경제",
      "date": "20260930",
      "url": "https://n.news.naver.com/mnews/article/015/0005337738"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/222080/news"
  },
  "아스트": {
    "company": "아스트",
    "code": "067390",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=067390",
    "news": {
      "title": "아스트, 워크아웃 만기 앞두고 1분기 최대 실적…민항기 넘어 방산 겨...",
      "office": "블로터",
      "date": "20260521",
      "url": "https://n.news.naver.com/mnews/article/293/0000085049"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/067390/news"
  },
  "알테오젠": {
    "company": "알테오젠",
    "code": "196170",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=196170",
    "news": {
      "title": "알테오젠, 장 초반 6% 급락…'키트루다 SC' 유럽 판매 제동",
      "office": "한국경제",
      "date": "20261008",
      "url": "https://n.news.naver.com/mnews/article/015/0005340429"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/196170/news"
  },
  "에너토크": {
    "company": "에너토크",
    "code": "019990",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=019990",
    "news": {
      "title": "에너토크, 우즈베키스탄 'AI 스마트 열에너지 플랫폼' 사업 참여",
      "office": "MBN",
      "date": "20260908",
      "url": "https://n.news.naver.com/mnews/article/057/0001967921"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/019990/news"
  },
  "에스비비테크": {
    "company": "에스비비테크",
    "code": "389500",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=389500",
    "news": {
      "title": "로봇 대세 속 적자 탈출 숙제…에스비비테크의 비밀병기는",
      "office": "이데일리",
      "date": "20260821",
      "url": "https://n.news.naver.com/mnews/article/018/0006355642"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/389500/news"
  },
  "에스오에스랩": {
    "company": "에스오에스랩",
    "code": "464080",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=464080",
    "news": {
      "title": "정지성 에스오에스랩 대표, ‘카카오 AI 돛 서밋’서 기술창업 성장 ...",
      "office": "이데일리",
      "date": "20261001",
      "url": "https://n.news.naver.com/mnews/article/018/0006378833"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/464080/news"
  },
  "에스티팜": {
    "company": "에스티팜",
    "code": "237690",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=237690",
    "news": {
      "title": "에스티팜, 913억원 올리고 수주로 RNA 치료제 생산 경쟁력 입증",
      "office": "파이낸셜뉴스",
      "date": "20260929",
      "url": "https://n.news.naver.com/mnews/article/014/0005582317"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/237690/news"
  },
  "에스피지": {
    "company": "에스피지",
    "code": "058610",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=058610",
    "news": {
      "title": "'매출 줄고 재고 는' 에스피지, 자산 3분의1이 재고",
      "office": "동행미디어 시대",
      "date": "20261007",
      "url": "https://n.news.naver.com/mnews/article/417/0001160233"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/058610/news"
  },
  "에이디테크놀로지": {
    "company": "에이디테크놀로지",
    "code": "200710",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=200710",
    "news": {
      "title": "삼성·SK, SEDEX서 차세대 HBM 격돌…AI칩·소부장도 총출동",
      "office": "아이뉴스24",
      "date": "20261005",
      "url": "https://n.news.naver.com/mnews/article/031/0001063506"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/200710/news"
  },
  "에이비엘바이오": {
    "company": "에이비엘바이오",
    "code": "298380",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=298380",
    "news": {
      "title": "\"릴리와 공동연구 종료\" 펩트론 주가 '뚝'…일부 제약바이오株 '흔들...",
      "office": "머니투데이",
      "date": "20261008",
      "url": "https://n.news.naver.com/mnews/article/008/0005423693"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/298380/news"
  },
  "에코프로비엠": {
    "company": "에코프로비엠",
    "code": "247540",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=247540",
    "news": {
      "title": "[이 시각 시황] 삼성전자 어닝서프라이즈에도 시장 하락…2차전지·반...",
      "office": "SBS Biz",
      "date": "20261008",
      "url": "https://n.news.naver.com/mnews/article/374/0000536824"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/247540/news"
  },
  "엔젤로보틱스": {
    "company": "엔젤로보틱스",
    "code": "455900",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=455900",
    "news": {
      "title": "엔젤로보틱스, 피지컬 AI 연구용 웨어러블 로봇 공개",
      "office": "뉴스1",
      "date": "20260929",
      "url": "https://n.news.naver.com/mnews/article/421/0009198025"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/455900/news"
  },
  "엔켐": {
    "company": "엔켐",
    "code": "348370",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=348370",
    "news": {
      "title": "엔켐, 출하 확대 효과 본격화…2분기 매출 22%↑·수익성 개선",
      "office": "한경비즈니스",
      "date": "20260818",
      "url": "https://n.news.naver.com/mnews/article/050/0000109760"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/348370/news"
  },
  "엘앤에프": {
    "company": "엘앤에프",
    "code": "066970",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=066970",
    "news": {
      "title": "포스코퓨처엠·엘앤에프, LFP 전환 속도…K 배터리, 美 ESS 양산 본격화",
      "office": "뉴스1",
      "date": "20261006",
      "url": "https://n.news.naver.com/mnews/article/421/0009210458"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/066970/news"
  },
  "오르비텍": {
    "company": "오르비텍",
    "code": "046120",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=046120",
    "news": {
      "title": "오르비텍, 파인테크닉스 414만주 매각 완료…“신사업 재원 확보”",
      "office": "한국경제",
      "date": "20261001",
      "url": "https://n.news.naver.com/mnews/article/015/0005338135"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/046120/news"
  },
  "오픈엣지테크놀로지": {
    "company": "오픈엣지테크놀로지",
    "code": "394280",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=394280",
    "news": {
      "title": "오픈엣지테크놀로지, AI 반도체 기업과 67억 규모 계약 체결",
      "office": "이데일리",
      "date": "20261002",
      "url": "https://n.news.naver.com/mnews/article/018/0006379759"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/394280/news"
  },
  "올릭스": {
    "company": "올릭스",
    "code": "226950",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=226950",
    "news": {
      "title": "[임상 업데이트] 올릭스, 황반변성 치료제 ‘OLX301A’ 호주 2a상 신청",
      "office": "이데일리",
      "date": "20260920",
      "url": "https://n.news.naver.com/mnews/article/018/0006372755"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/226950/news"
  },
  "우리기술": {
    "company": "우리기술",
    "code": "032820",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=032820",
    "news": {
      "title": "우리기술, 두산에너빌리티향 원전 가상화 DCS 개발용역 수주",
      "office": "이데일리",
      "date": "20260917",
      "url": "https://n.news.naver.com/mnews/article/018/0006370957"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/032820/news"
  },
  "우진": {
    "company": "우진",
    "code": "105840",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=105840",
    "news": {
      "title": "우진, 한국수력원자력과 109억 규모 공급계약 체결",
      "office": "헤럴드경제",
      "date": "20260617",
      "url": "https://n.news.naver.com/mnews/article/016/0002657906"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/105840/news"
  },
  "우진엔텍": {
    "company": "우진엔텍",
    "code": "457550",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=457550",
    "news": {
      "title": "우진엔텍, 원전 방사선감시계통 MI 케이블 어셈블리 국산화",
      "office": "뉴시스",
      "date": "20260714",
      "url": "https://n.news.naver.com/mnews/article/003/0014064540"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/457550/news"
  },
  "원익머트리얼즈": {
    "company": "원익머트리얼즈",
    "code": "104830",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=104830",
    "news": {
      "title": "“반도체용 특수가스 기업 원익머트리얼즈, 영업이익 올해 673억→ 내...",
      "office": "주간동아",
      "date": "20260821",
      "url": "https://n.news.naver.com/mnews/article/037/0000038708"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/104830/news"
  },
  "원익피앤이": {
    "company": "원익피앤이",
    "code": "217820",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=217820",
    "news": {
      "title": "원익피앤이·씨엘모빌리티, '충전 연동형 EV 플릿 통합관제' 공동 개발...",
      "office": "한경비즈니스",
      "date": "20260819",
      "url": "https://n.news.naver.com/mnews/article/050/0000109875"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/217820/news"
  },
  "원익IPS": {
    "company": "원익IPS",
    "code": "240810",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=240810",
    "news": {
      "title": "삼성전자, 실적 발표날이 더 위험하다?…골드만삭스 “8일 변동성 확...",
      "office": "조선비즈",
      "date": "20261007",
      "url": "https://n.news.naver.com/mnews/article/366/0001196737"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/240810/news"
  },
  "유진테크": {
    "company": "유진테크",
    "code": "084370",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=084370",
    "news": {
      "title": "\"삼전닉스보다 더 뜨겁다\"…마이크론 깜짝 실적에 뜨는 소부장[종목e...",
      "office": "이데일리",
      "date": "20261003",
      "url": "https://n.news.naver.com/mnews/article/018/0006380012"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/084370/news"
  },
  "유한양행": {
    "company": "유한양행",
    "code": "000100",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=000100",
    "news": {
      "title": "유한양행, ‘센스밸런스 구미데이 비건 멀티비타민&미네랄’ 새롭게 ...",
      "office": "한국경제",
      "date": "20261008",
      "url": "https://n.news.naver.com/mnews/article/015/0005340404"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/000100/news"
  },
  "이노스페이스": {
    "company": "이노스페이스",
    "code": "462350",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=462350",
    "news": {
      "title": "11월 재발사 앞둔 이노스페이스… 리픽싱 바닥 찍자 ‘손절성 전환 러...",
      "office": "조선비즈",
      "date": "20261002",
      "url": "https://n.news.naver.com/mnews/article/366/0001195940"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/462350/news"
  },
  "이수페타시스": {
    "company": "이수페타시스",
    "code": "007660",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=007660",
    "news": {
      "title": "대구 지역 상장사 시가총액 2분기 연속 하락···이수페타시스 1위 유...",
      "office": "대구MBC",
      "date": "20261006",
      "url": "https://n.news.naver.com/mnews/article/657/0000056037"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/007660/news"
  },
  "인텔리안테크": {
    "company": "인텔리안테크",
    "code": "189300",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=189300",
    "news": {
      "title": "인텔리안테크, 텔레샛 유럽 첫 게이트웨이 공급…LEO 협력 본격화",
      "office": "전자신문",
      "date": "20260921",
      "url": "https://n.news.naver.com/mnews/article/030/0003468817"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/189300/news"
  },
  "일진전기": {
    "company": "일진전기",
    "code": "103590",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=103590",
    "news": {
      "title": "[클릭 e종목]일진전기, 전력 인프라 투자 확대 수혜 기대",
      "office": "아시아경제",
      "date": "20261008",
      "url": "https://n.news.naver.com/mnews/article/277/0005825939"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/103590/news"
  },
  "제노코": {
    "company": "제노코",
    "code": "361390",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=361390",
    "news": {
      "title": "'CB 오버행 변수' 제노코, 하반기 실적 반등 앞두고 물량 부담",
      "office": "동행미디어 시대",
      "date": "20260818",
      "url": "https://n.news.naver.com/mnews/article/417/0001155587"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/361390/news"
  },
  "제주반도체": {
    "company": "제주반도체",
    "code": "080220",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=080220",
    "news": {
      "title": "‘자사주 매입 끝물’ 삼전닉스 팔고…삼성전기·LG전자 담는 상위 1%...",
      "office": "서울경제",
      "date": "20261006",
      "url": "https://n.news.naver.com/mnews/article/011/0004668509"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/080220/news"
  },
  "주성엔지니어링": {
    "company": "주성엔지니어링",
    "code": "036930",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=036930",
    "news": {
      "title": "[이 시각 시황] 삼성전자 어닝서프라이즈에도 시장 하락…2차전지·반...",
      "office": "SBS Biz",
      "date": "20261008",
      "url": "https://n.news.naver.com/mnews/article/374/0000536824"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/036930/news"
  },
  "지씨셀": {
    "company": "지씨셀",
    "code": "144510",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=144510",
    "news": {
      "title": "지씨셀, 신약 후보물질 ‘GCC2005’ 임상 1b상 첫 투약 마쳐",
      "office": "디지털타임스",
      "date": "20261007",
      "url": "https://n.news.naver.com/mnews/article/029/0003052011"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/144510/news"
  },
  "지엔씨에너지": {
    "company": "지엔씨에너지",
    "code": "119850",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=119850",
    "news": {
      "title": "지엔씨에너지, AI데이터센터發 수주 랠리 본격화…\"내년 더 빨라진다...",
      "office": "이데일리",
      "date": "20260928",
      "url": "https://n.news.naver.com/mnews/article/018/0006376101"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/119850/news"
  },
  "천보": {
    "company": "천보",
    "code": "278280",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=278280",
    "news": {
      "title": "동화일렉트로·피지티·천보, '북미 배터리 순환형 공급망' 협력",
      "office": "뉴스1",
      "date": "20260210",
      "url": "https://n.news.naver.com/mnews/article/421/0008765379"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/278280/news"
  },
  "칩스앤미디어": {
    "company": "칩스앤미디어",
    "code": "094360",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=094360",
    "news": {
      "title": "칩스앤미디어, AI 반도체 메모리 병목 해소 '데이터 압축 IP' 공개",
      "office": "아시아경제",
      "date": "20261007",
      "url": "https://n.news.naver.com/mnews/article/277/0005825368"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/094360/news"
  },
  "컨텍": {
    "company": "컨텍",
    "code": "451760",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=451760",
    "news": {
      "title": "컨텍·AP위성, 카자흐스탄 '갈람' 지분 투자...민간 우주기술과 국영 ...",
      "office": "한국경제TV",
      "date": "20260917",
      "url": "https://n.news.naver.com/mnews/article/215/0001266313"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/451760/news"
  },
  "켄코아에어로스페이스": {
    "company": "켄코아에어로스페이스",
    "code": "274090",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=274090",
    "news": {
      "title": "[창간기획]AI로 중처법 넘는다/켄코아에어로스페이스, AI가 작업자 움...",
      "office": "전자신문",
      "date": "20260921",
      "url": "https://n.news.naver.com/mnews/article/030/0003468777"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/274090/news"
  },
  "코스모신소재": {
    "company": "코스모신소재",
    "code": "005070",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=005070",
    "news": {
      "title": "코스모신소재, 150억 규모 피노 지분 인수계약 체결",
      "office": "뉴시스",
      "date": "20260907",
      "url": "https://n.news.naver.com/mnews/article/003/0014173043"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/005070/news"
  },
  "큐렉소": {
    "company": "큐렉소",
    "code": "060280",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=060280",
    "news": {
      "title": "큐렉소·에스오에스랩, 수술·의료로봇 공간지능 솔루션 개발 MOU 체결",
      "office": "이데일리",
      "date": "20260826",
      "url": "https://n.news.naver.com/mnews/article/018/0006358187"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/060280/news"
  },
  "큐로셀": {
    "company": "큐로셀",
    "code": "372320",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=372320",
    "news": {
      "title": "큐로셀 국산 CAR-T 급여 ‘성큼’…유한양행 API 수주도 순항 [바이오...",
      "office": "이데일리",
      "date": "20260906",
      "url": "https://n.news.naver.com/mnews/article/018/0006364319"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/372320/news"
  },
  "클로봇": {
    "company": "클로봇",
    "code": "466100",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=466100",
    "news": {
      "title": "클로봇, DLS 인수 마무리…물류자동화 시너지 낸다",
      "office": "아이뉴스24",
      "date": "20260901",
      "url": "https://n.news.naver.com/mnews/article/031/0001054127"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/466100/news"
  },
  "태성": {
    "company": "태성",
    "code": "323280",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=323280",
    "news": {
      "title": "태성, 9월 수주 2200억원 돌파…\"지난해 연간 매출액 5.8배\"",
      "office": "아시아경제",
      "date": "20260904",
      "url": "https://n.news.naver.com/mnews/article/277/0005811825"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/323280/news"
  },
  "테스": {
    "company": "테스",
    "code": "095610",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=095610",
    "news": {
      "title": "“테슬라 AI5 수주 가시화” 두산테스나, 2027년 영업이익 220% 증가 전...",
      "office": "주간동아",
      "date": "20261006",
      "url": "https://n.news.naver.com/mnews/article/037/0000038936"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/095610/news"
  },
  "테크윙": {
    "company": "테크윙",
    "code": "089030",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=089030",
    "news": {
      "title": "AI 개발 늦추더라도…삼전·닉스 \"아직 저렴하다\"는 이유 [B급기자의 ...",
      "office": "한국경제TV",
      "date": "20260916",
      "url": "https://n.news.naver.com/mnews/article/215/0001266147"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/089030/news"
  },
  "텔레칩스": {
    "company": "텔레칩스",
    "code": "054450",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=054450",
    "news": {
      "title": "“글로벌 차량용 AP 경쟁력 확인”…텔레칩스, 인도 완성차 업체 공급...",
      "office": "문화일보",
      "date": "20260914",
      "url": "https://n.news.naver.com/mnews/article/021/0002818621"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/054450/news"
  },
  "툴젠": {
    "company": "툴젠",
    "code": "199800",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=199800",
    "news": {
      "title": "툴젠, 심혈관질환 유전자치료제 개발 속도…\"내년 美 임상 신청\"",
      "office": "이데일리",
      "date": "20260903",
      "url": "https://n.news.naver.com/mnews/article/018/0006363281"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/199800/news"
  },
  "티로보틱스": {
    "company": "티로보틱스",
    "code": "117730",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=117730",
    "news": {
      "title": "티로보틱스, AI 휴머노이드 대기업 제조라인서 실증…45억원 국책과제...",
      "office": "매일경제",
      "date": "20260929",
      "url": "https://n.news.naver.com/mnews/article/009/0005741174"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/117730/news"
  },
  "티씨케이": {
    "company": "티씨케이",
    "code": "064760",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=064760",
    "news": {
      "title": "[클릭 e종목]티씨케이, '뮤즈'발 에이전틱 AI 확산…수혜 기대",
      "office": "아시아경제",
      "date": "20260930",
      "url": "https://n.news.naver.com/mnews/article/277/0005822453"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/064760/news"
  },
  "파마리서치": {
    "company": "파마리서치",
    "code": "214450",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=214450",
    "news": {
      "title": "파마리서치, '리쥬란' 유사 상표 소송 승소…\"유사 제품 강력 대처\"",
      "office": "뉴스1",
      "date": "20261008",
      "url": "https://n.news.naver.com/mnews/article/421/0009216497"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/214450/news"
  },
  "퍼스텍": {
    "company": "퍼스텍",
    "code": "010820",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=010820",
    "news": {
      "title": "종전 MOU에 재건주 '들썩'…퍼스텍 '上'·대우건설 24%↑",
      "office": "뉴시스",
      "date": "20260616",
      "url": "https://n.news.naver.com/mnews/article/003/0014008443"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/010820/news"
  },
  "펩트론": {
    "company": "펩트론",
    "code": "087010",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=087010",
    "news": {
      "title": "\"릴리와의 본계약 불발\"…펩트론 주가 26% 급락",
      "office": "한국경제",
      "date": "20261007",
      "url": "https://n.news.naver.com/mnews/article/015/0005340295"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/087010/news"
  },
  "포스코퓨처엠": {
    "company": "포스코퓨처엠",
    "code": "003670",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=003670",
    "news": {
      "title": "SK온 이어 삼성SDI도 확보…포스코퓨처엠, LFP 양극재 공급 영토 확장...",
      "office": "디지털데일리",
      "date": "20261007",
      "url": "https://n.news.naver.com/mnews/article/138/0002243922"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/003670/news"
  },
  "피에스케이": {
    "company": "피에스케이",
    "code": "319660",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=319660",
    "news": {
      "title": "“피에스케이, 글로벌 설비투자 확대 수혜…목표가 22만원 유지”-현...",
      "office": "이데일리",
      "date": "20260929",
      "url": "https://n.news.naver.com/mnews/article/018/0006376785"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/319660/news"
  },
  "피엔티": {
    "company": "피엔티",
    "code": "137400",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=137400",
    "news": {
      "title": "미래에셋, 피엔티 목표가↓…\"3분기에는 영업이익 회복 전망\"",
      "office": "연합뉴스",
      "date": "20260901",
      "url": "https://n.news.naver.com/mnews/article/001/0016281422"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/137400/news"
  },
  "필옵틱스": {
    "company": "필옵틱스",
    "code": "161580",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=161580",
    "news": {
      "title": "[애프터마켓 리뷰] 필옵틱스, 차세대 TGV 장비 납품 수주 성공",
      "office": "SBS Biz",
      "date": "20260930",
      "url": "https://n.news.naver.com/mnews/article/374/0000535485"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/161580/news"
  },
  "하나마이크론": {
    "company": "하나마이크론",
    "code": "067310",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=067310",
    "news": {
      "title": "삼성전기, AI 타고 ‘퀀텀점프’…글로벌 시장 점유율 40% 독주",
      "office": "서울경제",
      "date": "20261007",
      "url": "https://n.news.naver.com/mnews/article/011/0004668890"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/067310/news"
  },
  "하나머티리얼즈": {
    "company": "하나머티리얼즈",
    "code": "166090",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=166090",
    "news": {
      "title": "하나머티리얼즈, 메모리 증설에 Si 파츠 수요↑…내년 실적 가속-SK",
      "office": "이데일리",
      "date": "20260903",
      "url": "https://n.news.naver.com/mnews/article/018/0006362809"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/166090/news"
  },
  "하이젠알앤엠": {
    "company": "하이젠알앤엠",
    "code": "160190",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=160190",
    "news": {
      "title": "모터 기술력으로 지능형 엑추에이터 개발…하이젠알앤엠 ‘로봇 관절...",
      "office": "매일경제",
      "date": "20260915",
      "url": "https://n.news.naver.com/mnews/article/009/0005735307"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/160190/news"
  },
  "하이즈항공": {
    "company": "하이즈항공",
    "code": "221840",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=221840",
    "news": {
      "title": "하이즈항공, 대한항공에 보잉 치누크 헬기 부품 공급…51억원 규모",
      "office": "동행미디어 시대",
      "date": "20260512",
      "url": "https://n.news.naver.com/mnews/article/417/0001142773"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/221840/news"
  },
  "한국항공우주": {
    "company": "한국항공우주",
    "code": "047810",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=047810",
    "news": {
      "title": "한국항공우주, 3Q 실적 기대치 하회 전망…목표가↓-유안타",
      "office": "이데일리",
      "date": "20261008",
      "url": "https://n.news.naver.com/mnews/article/018/0006383309"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/047810/news"
  },
  "한미반도체": {
    "company": "한미반도체",
    "code": "042700",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=042700",
    "news": {
      "title": "한미반도체, 삼성전기에 245억 반도체 장비 공급",
      "office": "서울신문",
      "date": "20261007",
      "url": "https://n.news.naver.com/mnews/article/081/0003686639"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/042700/news"
  },
  "한솔케미칼": {
    "company": "한솔케미칼",
    "code": "014680",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=014680",
    "news": {
      "title": "한솔케미칼, 대만에 340억원 규모 반도체 소재 기지 투자 승인",
      "office": "전자신문",
      "date": "20261006",
      "url": "https://n.news.naver.com/mnews/article/030/0003472721"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/014680/news"
  },
  "한전기술": {
    "company": "한전기술",
    "code": "052690",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=052690",
    "news": {
      "title": "한전기술, 50년 설계자산 AI 전환…원전 설계 노하우 협력사와 공유",
      "office": "디지털타임스",
      "date": "20261007",
      "url": "https://n.news.naver.com/mnews/article/029/0003052034"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/052690/news"
  },
  "한전산업": {
    "company": "한전산업",
    "code": "130660",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=130660",
    "news": {
      "title": "두 달 전엔 반토막…대미 투자 수혜 기대에 되살아난 이 섹터[왜웃株...",
      "office": "매일신문",
      "date": "20260910",
      "url": "https://n.news.naver.com/mnews/article/088/0001027714"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/130660/news"
  },
  "한전KPS": {
    "company": "한전KPS",
    "code": "051600",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=051600",
    "news": {
      "title": "한전KPS “AI감사 부작용 AI로 막는다”…방어체계 구축 착수",
      "office": "부산일보",
      "date": "20261007",
      "url": "https://n.news.naver.com/mnews/article/082/0001401625"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/051600/news"
  },
  "한중엔시에스": {
    "company": "한중엔시에스",
    "code": "107640",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=107640",
    "news": {
      "title": "한중엔시에스, 美 자회사에 158억 출자…신규시설 투자",
      "office": "이데일리",
      "date": "20260917",
      "url": "https://n.news.naver.com/mnews/article/018/0006371096"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/107640/news"
  },
  "한화에어로스페이스": {
    "company": "한화에어로스페이스",
    "code": "012450",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=012450",
    "news": {
      "title": "\"K방산, AI·첨단기술 적용이 병목 가능성... 협력 중기와 상생 방안 ...",
      "office": "한국일보",
      "date": "20261008",
      "url": "https://n.news.naver.com/mnews/article/469/0000958307"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/012450/news"
  },
  "현대건설": {
    "company": "현대건설",
    "code": "000720",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=000720",
    "news": {
      "title": "현대건설, 네덜란드 신규 원전 기본설계 착수… 유럽 원전 영토 확장...",
      "office": "이코노미스트",
      "date": "20261008",
      "url": "https://n.news.naver.com/mnews/article/243/0000103977"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/000720/news"
  },
  "현대무벡스": {
    "company": "현대무벡스",
    "code": "319400",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=319400",
    "news": {
      "title": "현대무벡스, 금호타이어 함평 신공장 스마트 물류 구축 사업 수주",
      "office": "스포츠조선",
      "date": "20261001",
      "url": "https://n.news.naver.com/mnews/article/076/0004451809"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/319400/news"
  },
  "효성중공업": {
    "company": "효성중공업",
    "code": "298040",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=298040",
    "news": {
      "title": "\"흔들리지 마세요, 400만닉스 갑니다\"…\"효성중공업, 실적 하회에도 중...",
      "office": "파이낸셜뉴스",
      "date": "20261007",
      "url": "https://n.news.naver.com/mnews/article/014/0005586037"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/298040/news"
  },
  "휴니드": {
    "company": "휴니드",
    "code": "005870",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=005870",
    "news": {
      "title": "휴니드, 한 달간 美 보잉향 공급계약 3건 수주",
      "office": "블로터",
      "date": "20260605",
      "url": "https://n.news.naver.com/mnews/article/293/0000085842"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/005870/news"
  },
  "휴젤": {
    "company": "휴젤",
    "code": "145020",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=145020",
    "news": {
      "title": "[클릭 e종목]휴젤, 실적 진통 후 중장기 성장 기대…목표가↓",
      "office": "아시아경제",
      "date": "20260921",
      "url": "https://n.news.naver.com/mnews/article/277/0005819471"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/145020/news"
  },
  "AP위성": {
    "company": "AP위성",
    "code": "211270",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=211270",
    "news": {
      "title": "컨텍·AP위성, 카자흐스탄 '갈람' 지분 투자...민간 우주기술과 국영 ...",
      "office": "한국경제TV",
      "date": "20260917",
      "url": "https://n.news.naver.com/mnews/article/215/0001266313"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/211270/news"
  },
  "HD현대일렉트릭": {
    "company": "HD현대일렉트릭",
    "code": "267260",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=267260",
    "news": {
      "title": "대신證 \"HD현대일렉트릭, 환율 여파에 3Q 실적 저조…목표가↓\"",
      "office": "뉴스1",
      "date": "20261007",
      "url": "https://n.news.naver.com/mnews/article/421/0009213356"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/267260/news"
  },
  "HK이노엔": {
    "company": "HK이노엔",
    "code": "195940",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=195940",
    "news": {
      "title": "“청소년 비만 치료 선택지 넓힌다”…HK이노엔, GLP-1 신약 임상서 체...",
      "office": "동아일보",
      "date": "20261007",
      "url": "https://n.news.naver.com/mnews/article/020/0003753295"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/195940/news"
  },
  "HPSP": {
    "company": "HPSP",
    "code": "403870",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=403870",
    "news": {
      "title": "\"HPSP, 파운드리 넘어 메모리 반도체까지 확장…목표가↑\"-KB",
      "office": "한국경제",
      "date": "20261006",
      "url": "https://n.news.naver.com/mnews/article/015/0005339371"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/403870/news"
  },
  "ISC": {
    "company": "ISC",
    "code": "095340",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=095340",
    "news": {
      "title": "ISC, 1000억원 규모 반도체 소켓 투자 추진…AI 반도체 수요 대응",
      "office": "디지털데일리",
      "date": "20260929",
      "url": "https://n.news.naver.com/mnews/article/138/0002242966"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/095340/news"
  },
  "LG에너지솔루션": {
    "company": "LG에너지솔루션",
    "code": "373220",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=373220",
    "news": {
      "title": "LG에너지솔루션, 캐나다산 리튬 정광 24만톤 확보…북미 공급망 강화",
      "office": "디지털데일리",
      "date": "20261008",
      "url": "https://n.news.naver.com/mnews/article/138/0002244058"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/373220/news"
  },
  "LIG넥스원": {
    "company": "LIG넥스원",
    "code": "079550",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=079550",
    "news": {
      "title": "격랑의 중동서 K방산 성공하려면… \"공급자 넘어 동반자 돼야\"",
      "office": "한국일보",
      "date": "20261007",
      "url": "https://n.news.naver.com/mnews/article/469/0000958280"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/079550/news"
  },
  "LS": {
    "company": "LS",
    "code": "006260",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=006260",
    "news": {
      "title": "LS證 \"코스맥스, 목표가 40만원으로 상향…사상 최대 분기 실적 기대\"",
      "office": "뉴시스",
      "date": "20261008",
      "url": "https://n.news.naver.com/mnews/article/003/0014240632"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/006260/news"
  },
  "LS ELECTRIC": {
    "company": "LS ELECTRIC",
    "code": "010120",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=010120",
    "news": {
      "title": "LS일렉, 대만 최대 석화기업과 합작법인 설립 계약",
      "office": "동아일보",
      "date": "20261008",
      "url": "https://n.news.naver.com/mnews/article/020/0003753492"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/010120/news"
  },
  "LS마린솔루션": {
    "company": "LS마린솔루션",
    "code": "060370",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=060370",
    "news": {
      "title": "해상풍력 발주 본격화…LS마린솔루션, 수주·선박 투자로 대응",
      "office": "디지털타임스",
      "date": "20261002",
      "url": "https://n.news.naver.com/mnews/article/029/0003051134"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/060370/news"
  },
  "LS에코에너지": {
    "company": "LS에코에너지",
    "code": "229640",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=229640",
    "news": {
      "title": "LS에코에너지, AIDC용 대용량 버스덕트 투자…생산능력 2배 확대",
      "office": "디지털데일리",
      "date": "20261007",
      "url": "https://n.news.naver.com/mnews/article/138/0002243993"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/229640/news"
  },
  "SK바이오사이언스": {
    "company": "SK바이오사이언스",
    "code": "302440",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=302440",
    "news": {
      "title": "SK바이오사이언스, 獨 IDT 인수 2년 만에 흑자… 글로벌 사업 ‘본격화...",
      "office": "서울신문",
      "date": "20261008",
      "url": "https://n.news.naver.com/mnews/article/081/0003687108"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/302440/news"
  },
  "SK바이오팜": {
    "company": "SK바이오팜",
    "code": "326030",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=326030",
    "news": {
      "title": "SK바이오팜 '후속 신약' 확보 속도…제품 다변화 이끄는 최윤정",
      "office": "더팩트",
      "date": "20261006",
      "url": "https://n.news.naver.com/mnews/article/629/0000539743"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/326030/news"
  },
  "SK이노베이션": {
    "company": "SK이노베이션",
    "code": "096770",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=096770",
    "news": {
      "title": "\"SK이노베이션, 바로사 LNG 도입으로 이익 확대…목표가 20%↑\"",
      "office": "머니투데이",
      "date": "20261008",
      "url": "https://n.news.naver.com/mnews/article/008/0005423671"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/096770/news"
  },
  "SK하이닉스": {
    "company": "SK하이닉스",
    "code": "000660",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=000660",
    "news": {
      "title": "‘AI 반도체 열풍 효과’…3분기 반도체 대기업 공고 102% 증가",
      "office": "이코노미스트",
      "date": "20261008",
      "url": "https://n.news.naver.com/mnews/article/243/0000103978"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/000660/news"
  },
  "SKC": {
    "company": "SKC",
    "code": "011790",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=011790",
    "news": {
      "title": "'화학·필름' SKC의 변신…AI 반도체 소재로 사업 중심 이동",
      "office": "뉴시스",
      "date": "20260929",
      "url": "https://n.news.naver.com/mnews/article/003/0014220530"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/011790/news"
  },
  "SNT에너지": {
    "company": "SNT에너지",
    "code": "100840",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=100840",
    "news": {
      "title": "SNT에너지, 대산 LNG 사업에 305억원 규모 보일러 공급 완료",
      "office": "이데일리",
      "date": "20260914",
      "url": "https://n.news.naver.com/mnews/article/018/0006369286"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/100840/news"
  }
};
