// Generated by scripts/update-market-sources.mjs on 2026-08-27.
export type BrokerReport = { title: string; broker: string; date: string; url: string; pdfUrl: string };
export type StockNews = { title: string; office: string; date: string; url: string };
export type MarketSourceRecord = { company: string; code: string; updatedAt: string; report: BrokerReport | null; reportListUrl: string; news: StockNews | null; newsListUrl: string; error?: string };

export const marketSourcesByStock: Record<string, MarketSourceRecord> = {
  "가온전선": {
    "company": "가온전선",
    "code": "000500",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=000500",
    "news": {
      "title": "가온전선, 캐나다 전력시장 첫 진출…북미 매출 50% 성장 전망",
      "office": "데일리안",
      "date": "20260909",
      "url": "https://n.news.naver.com/mnews/article/119/0003130944"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/000500/news"
  },
  "가온칩스": {
    "company": "가온칩스",
    "code": "399720",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=399720",
    "news": {
      "title": "[오늘장 탑픽] 삼성 파운드리 흑자 전환…가온칩스·에이직랜드 주목",
      "office": "SBS Biz",
      "date": "20260715",
      "url": "https://n.news.naver.com/mnews/article/374/0000521782"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/399720/news"
  },
  "고영": {
    "company": "고영",
    "code": "098460",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=098460",
    "news": {
      "title": "고영, AIDC·반도체 수요 대응 위해 294억 시설투자",
      "office": "이데일리",
      "date": "20260806",
      "url": "https://n.news.naver.com/mnews/article/018/0006346288"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/098460/news"
  },
  "네패스아크": {
    "company": "네패스아크",
    "code": "330860",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=330860",
    "news": {
      "title": "네패스아크, 반도체 테스트 설비에 667억 투자 결정",
      "office": "블로터",
      "date": "20260526",
      "url": "https://n.news.naver.com/mnews/article/293/0000085285"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/330860/news"
  },
  "뉴로메카": {
    "company": "뉴로메카",
    "code": "348340",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=348340",
    "news": {
      "title": "포항에 주문형 로봇 생산시설 구축…1천800억원 투자",
      "office": "연합뉴스",
      "date": "20260910",
      "url": "https://n.news.naver.com/mnews/article/001/0016303256"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/348340/news"
  },
  "대덕전자": {
    "company": "대덕전자",
    "code": "353200",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=353200",
    "news": {
      "title": "‘제2의 HBM’ 소캠株 불기둥…대덕전자 상한가[특징주]",
      "office": "이데일리",
      "date": "20260731",
      "url": "https://n.news.naver.com/mnews/article/018/0006341005"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/353200/news"
  },
  "대주전자재료": {
    "company": "대주전자재료",
    "code": "078600",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=078600",
    "news": {
      "title": "대주전자재료, 북미 우주항공기업 협력 확대…음극재·CNT 샘플 공급",
      "office": "이데일리",
      "date": "20260821",
      "url": "https://n.news.naver.com/mnews/article/018/0006355415"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/078600/news"
  },
  "대한전선": {
    "company": "대한전선",
    "code": "001440",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=001440",
    "news": {
      "title": "대한전선, 구리값 상승 '양날의 검'…400억 공모채로 원재료비 수혈",
      "office": "블로터",
      "date": "20260911",
      "url": "https://n.news.naver.com/mnews/article/293/0000090342"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/001440/news"
  },
  "더블유씨피": {
    "company": "더블유씨피",
    "code": "393890",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=393890",
    "news": {
      "title": "더블유씨피 2분기 영업손실 40%↓…\"3분기 실적 반등 전환점\"",
      "office": "아시아경제",
      "date": "20260807",
      "url": "https://n.news.naver.com/mnews/article/277/0005800371"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/393890/news"
  },
  "동진쎄미켐": {
    "company": "동진쎄미켐",
    "code": "005290",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=005290",
    "news": {
      "title": "동진쎄미켐, 반도체가 끌고 中 매각 밀었다…상반기 순익 급증 이유 ...",
      "office": "뉴스1",
      "date": "20260831",
      "url": "https://n.news.naver.com/mnews/article/421/0009140551"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/005290/news"
  },
  "두산로보틱스": {
    "company": "두산로보틱스",
    "code": "454910",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=454910",
    "news": {
      "title": "김민표 두산로보틱스 대표 “피지컬AI, 특정 작업에 집중해야”",
      "office": "헤럴드경제",
      "date": "20260908",
      "url": "https://n.news.naver.com/mnews/article/016/0002694306"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/454910/news"
  },
  "두산에너빌리티": {
    "company": "두산에너빌리티",
    "code": "034020",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=034020",
    "news": {
      "title": "네팔 긴급구호대 2진 현지 합류…두산에너빌리티도 주말 수색 이어간...",
      "office": "디지털데일리",
      "date": "20260912",
      "url": "https://n.news.naver.com/mnews/article/138/0002241158"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/034020/news"
  },
  "두산테스나": {
    "company": "두산테스나",
    "code": "131970",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=131970",
    "news": {
      "title": "AI의 네번째 분기점?…자극받은 투자자에 반도체 '활짝'",
      "office": "머니투데이",
      "date": "20260907",
      "url": "https://n.news.naver.com/mnews/article/008/0005410478"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/131970/news"
  },
  "디앤디파마텍": {
    "company": "디앤디파마텍",
    "code": "347850",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=347850",
    "news": {
      "title": "디앤디파마텍 섬유화증 치료제, 日 물질특허 등록 “글로벌 임상 가속...",
      "office": "서울경제",
      "date": "20260911",
      "url": "https://n.news.naver.com/mnews/article/011/0004660900"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/347850/news"
  },
  "레인보우로보틱스": {
    "company": "레인보우로보틱스",
    "code": "277810",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=277810",
    "news": {
      "title": "삼성SDS 로봇 파트너사 어딘가 봤더니… 손·데이터 전문",
      "office": "서울경제",
      "date": "20260912",
      "url": "https://n.news.naver.com/mnews/article/011/0004661135"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/277810/news"
  },
  "로보스타": {
    "company": "로보스타",
    "code": "090360",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=090360",
    "news": {
      "title": "빅웨이브로보틱스 \"글로벌 피지컬 AI 플랫폼 도약\"[IPO톡톡]",
      "office": "한국경제TV",
      "date": "20260911",
      "url": "https://n.news.naver.com/mnews/article/215/0001265679"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/090360/news"
  },
  "로보티즈": {
    "company": "로보티즈",
    "code": "108490",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=108490",
    "news": {
      "title": "마이크로덕發 주문 폭주…로보티즈, 액추에이터 '공급 병목'[종목현미...",
      "office": "뉴스1",
      "date": "20260912",
      "url": "https://n.news.naver.com/mnews/article/421/0009165997"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/108490/news"
  },
  "리가켐바이오": {
    "company": "리가켐바이오",
    "code": "141080",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=141080",
    "news": {
      "title": "[K바이오 돈의 경로] 수익원보다 먼저 넓어진 투자처｜에이비엘바이오...",
      "office": "블로터",
      "date": "20260911",
      "url": "https://n.news.naver.com/mnews/article/293/0000090322"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/141080/news"
  },
  "미래컴퍼니": {
    "company": "미래컴퍼니",
    "code": "049950",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=049950",
    "news": {
      "title": "[인터뷰] 김준구 미래컴퍼니 대표 “외산 독점 깨고 수술 로봇 국산화...",
      "office": "조선비즈",
      "date": "20260903",
      "url": "https://n.news.naver.com/mnews/article/366/0001190048"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/049950/news"
  },
  "바이오니아": {
    "company": "바이오니아",
    "code": "064550",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=064550",
    "news": {
      "title": "바이오니아, 검체 넣으면 PCR 결과까지 '자동으로'",
      "office": "매일경제",
      "date": "20260909",
      "url": "https://n.news.naver.com/mnews/article/009/0005732764"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/064550/news"
  },
  "비에이치아이": {
    "company": "비에이치아이",
    "code": "083650",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=083650",
    "news": {
      "title": "리딩투자증권 “비에이치아이, ‘대미투자 1호’ 수혜 가능성…美 가...",
      "office": "이데일리",
      "date": "20260910",
      "url": "https://n.news.naver.com/mnews/article/018/0006366656"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/083650/news"
  },
  "비츠로테크": {
    "company": "비츠로테크",
    "code": "042370",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=042370",
    "news": {
      "title": "반도체 다음은 ‘전력’ 슈퍼사이클…북미發 수주 훈풍, 韓 중기에도...",
      "office": "헤럴드경제",
      "date": "20260507",
      "url": "https://n.news.naver.com/mnews/article/016/0002639895"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/042370/news"
  },
  "산일전기": {
    "company": "산일전기",
    "code": "062040",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=062040",
    "news": {
      "title": "\"산일전기, 美 데이터센터 수주 증가 수혜…목표가 30만원\"",
      "office": "머니투데이",
      "date": "20260831",
      "url": "https://n.news.naver.com/mnews/article/008/0005406890"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/062040/news"
  },
  "삼성바이오로직스": {
    "company": "삼성바이오로직스",
    "code": "207940",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=207940",
    "news": {
      "title": "삼성, '70년 전통' 공채 이어간다…\"첨단기술 인재 대거 확대\"[AI로 달...",
      "office": "뉴시스",
      "date": "20260912",
      "url": "https://n.news.naver.com/mnews/article/003/0014185809"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/207940/news"
  },
  "삼성전기": {
    "company": "삼성전기",
    "code": "009150",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=009150",
    "news": {
      "title": "AI칩 커지자 '브리지' 뜬다…삼성전기·LG이노텍, 대면적 기판 승부[현...",
      "office": "아이뉴스24",
      "date": "20260912",
      "url": "https://n.news.naver.com/mnews/article/031/0001057769"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/009150/news"
  },
  "삼성전자": {
    "company": "삼성전자",
    "code": "005930",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=005930",
    "news": {
      "title": "“삼성전자, 40만원 전엔 절대 팔지 마라” 월요일 터질 게 터지나 ‘...",
      "office": "헤럴드경제",
      "date": "20260912",
      "url": "https://n.news.naver.com/mnews/article/016/0002696337"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/005930/news"
  },
  "삼성SDI": {
    "company": "삼성SDI",
    "code": "006400",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=006400",
    "news": {
      "title": "셀은 살아나는데 투자는 ‘아직’…K-배터리 생태계 반등 언제 [배터...",
      "office": "디지털데일리",
      "date": "20260911",
      "url": "https://n.news.naver.com/mnews/article/138/0002241108"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/006400/news"
  },
  "삼현": {
    "company": "삼현",
    "code": "437730",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=437730",
    "news": {
      "title": "“성능 산포 줄여 양산 경쟁력”…삼현, 휴머노이드 액추에이터 성장...",
      "office": "이데일리",
      "date": "20260907",
      "url": "https://n.news.naver.com/mnews/article/018/0006365081"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/437730/news"
  },
  "새빗켐": {
    "company": "새빗켐",
    "code": "107600",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=107600",
    "news": {
      "title": "'안정된 캐시카우·신사업'…새빗켐, 투트랙 전략으로 실적 반등 노려",
      "office": "동행미디어 시대",
      "date": "20260130",
      "url": "https://n.news.naver.com/mnews/article/417/0001127477"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/107600/news"
  },
  "서진시스템": {
    "company": "서진시스템",
    "code": "178320",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=178320",
    "news": {
      "title": "[메자닌 투자파일] 서진시스템, 2000억 수혈…재무 안정화 과제",
      "office": "블로터",
      "date": "20260831",
      "url": "https://n.news.naver.com/mnews/article/293/0000089782"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/178320/news"
  },
  "성일하이텍": {
    "company": "성일하이텍",
    "code": "365340",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=365340",
    "news": {
      "title": "디알티, 이차전지 재활용 고효율 BM 양산설비 본격 가동",
      "office": "조선비즈",
      "date": "20260909",
      "url": "https://n.news.naver.com/mnews/article/366/0001191218"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/365340/news"
  },
  "셀트리온": {
    "company": "셀트리온",
    "code": "068270",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=068270",
    "news": {
      "title": "셀트리온 ‘옴리클로’, 유럽 26개국 진출…“스페인 점유율 90% 넘어...",
      "office": "서울경제",
      "date": "20260910",
      "url": "https://n.news.naver.com/mnews/article/011/0004660641"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/068270/news"
  },
  "솔브레인": {
    "company": "솔브레인",
    "code": "357780",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=357780",
    "news": {
      "title": "메모리 호황에 '소모성 소재' 잘 팔린다…솔브레인·동진 실적 '쑥'",
      "office": "뉴스1",
      "date": "20260911",
      "url": "https://n.news.naver.com/mnews/article/421/0009164094"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/357780/news"
  },
  "신성에스티": {
    "company": "신성에스티",
    "code": "416180",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=416180",
    "news": {
      "title": "신성에스티, 북미 ESS 양산 확대 본격화",
      "office": "아시아경제",
      "date": "20260903",
      "url": "https://n.news.naver.com/mnews/article/277/0005811172"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/416180/news"
  },
  "심텍": {
    "company": "심텍",
    "code": "222800",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=222800",
    "news": {
      "title": "고유가·고금리에 7000선 내준 코스피…자사주 매입에 낙폭 축소[시황...",
      "office": "뉴스1",
      "date": "20260911",
      "url": "https://n.news.naver.com/mnews/article/421/0009165594"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/222800/news"
  },
  "쎄트렉아이": {
    "company": "쎄트렉아이",
    "code": "099320",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=099320",
    "news": {
      "title": "[스마트클라우드쇼 2026] 박원규 쎄트렉아이 전무 “AI 없이는 위성영...",
      "office": "조선비즈",
      "date": "20260826",
      "url": "https://n.news.naver.com/mnews/article/366/0001188504"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/099320/news"
  },
  "씨메스": {
    "company": "씨메스",
    "code": "475400",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=475400",
    "news": {
      "title": "씨메스로보틱스, 상반기 매출 95.2억…역대 최대",
      "office": "이데일리",
      "date": "20260813",
      "url": "https://n.news.naver.com/mnews/article/018/0006351003"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/475400/news"
  },
  "씨아이에스": {
    "company": "씨아이에스",
    "code": "222080",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=222080",
    "news": {
      "title": "2차전지 상위 10사 법인세 529억…매출 줄어도 전년비 37%↑ [2026년 상...",
      "office": "조세일보",
      "date": "20260907",
      "url": "https://n.news.naver.com/mnews/article/123/0002389694"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/222080/news"
  },
  "아스트": {
    "company": "아스트",
    "code": "067390",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=067390",
    "news": {
      "title": "아스트, 워크아웃 만기 앞두고 1분기 최대 실적…민항기 넘어 방산 겨...",
      "office": "블로터",
      "date": "20260521",
      "url": "https://n.news.naver.com/mnews/article/293/0000085049"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/067390/news"
  },
  "알테오젠": {
    "company": "알테오젠",
    "code": "196170",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=196170",
    "news": {
      "title": "씨어스, KRX 헬스케어 지수 편입…\"국내 유일 흑자 의료AI\"",
      "office": "머니투데이",
      "date": "20260911",
      "url": "https://n.news.naver.com/mnews/article/008/0005412626"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/196170/news"
  },
  "에너토크": {
    "company": "에너토크",
    "code": "019990",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=019990",
    "news": {
      "title": "에너토크, 우즈베키스탄 'AI 스마트 열에너지 플랫폼' 사업 참여",
      "office": "MBN",
      "date": "20260908",
      "url": "https://n.news.naver.com/mnews/article/057/0001967921"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/019990/news"
  },
  "에스비비테크": {
    "company": "에스비비테크",
    "code": "389500",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=389500",
    "news": {
      "title": "로봇 대세 속 적자 탈출 숙제…에스비비테크의 비밀병기는",
      "office": "이데일리",
      "date": "20260821",
      "url": "https://n.news.naver.com/mnews/article/018/0006355642"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/389500/news"
  },
  "에스오에스랩": {
    "company": "에스오에스랩",
    "code": "464080",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=464080",
    "news": {
      "title": "에스오에스랩, 경산시 강소형 스마트시티 조성사업 솔루션 공급",
      "office": "이데일리",
      "date": "20260908",
      "url": "https://n.news.naver.com/mnews/article/018/0006365428"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/464080/news"
  },
  "에스티팜": {
    "company": "에스티팜",
    "code": "237690",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=237690",
    "news": {
      "title": "GC녹십자 국산 mRNA 백신, 임상 2상 진입⋯연내 첫 투약",
      "office": "코메디닷컴",
      "date": "20260911",
      "url": "https://n.news.naver.com/mnews/article/296/0000104728"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/237690/news"
  },
  "에스피지": {
    "company": "에스피지",
    "code": "058610",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=058610",
    "news": {
      "title": "에스피지, 휴머노이드 카이로스에 정밀감속기 탑재",
      "office": "전자신문",
      "date": "20260908",
      "url": "https://n.news.naver.com/mnews/article/030/0003464888"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/058610/news"
  },
  "에이디테크놀로지": {
    "company": "에이디테크놀로지",
    "code": "200710",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=200710",
    "news": {
      "title": "반도체 훈풍 탄 디자인하우스, 상반기 실적 ‘훨훨’",
      "office": "파이낸셜뉴스",
      "date": "20260830",
      "url": "https://n.news.naver.com/mnews/article/014/0005568288"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/200710/news"
  },
  "에이비엘바이오": {
    "company": "에이비엘바이오",
    "code": "298380",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=298380",
    "news": {
      "title": "[K바이오 돈의 경로] 수익원보다 먼저 넓어진 투자처｜에이비엘바이오...",
      "office": "블로터",
      "date": "20260911",
      "url": "https://n.news.naver.com/mnews/article/293/0000090322"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/298380/news"
  },
  "에코프로비엠": {
    "company": "에코프로비엠",
    "code": "247540",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=247540",
    "news": {
      "title": "치솟는 유가·금리에 다시 '6천피'",
      "office": "한국경제TV",
      "date": "20260911",
      "url": "https://n.news.naver.com/mnews/article/215/0001265685"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/247540/news"
  },
  "엔젤로보틱스": {
    "company": "엔젤로보틱스",
    "code": "455900",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=455900",
    "news": {
      "title": "엔젤로보틱스, 베트남 '로봇재활 심포지엄' 성료…아세안 네트워크 강...",
      "office": "머니투데이",
      "date": "20260818",
      "url": "https://n.news.naver.com/mnews/article/008/0005401213"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/455900/news"
  },
  "엔켐": {
    "company": "엔켐",
    "code": "348370",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=348370",
    "news": {
      "title": "엔켐, 출하 확대 효과 본격화…2분기 매출 22%↑·수익성 개선",
      "office": "한경비즈니스",
      "date": "20260818",
      "url": "https://n.news.naver.com/mnews/article/050/0000109760"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/348370/news"
  },
  "엘앤에프": {
    "company": "엘앤에프",
    "code": "066970",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=066970",
    "news": {
      "title": "엘앤에프, 신산업 투자 앞두고 자금조달 속도…LFP·46파이 '초격차' ...",
      "office": "매일신문",
      "date": "20260909",
      "url": "https://n.news.naver.com/mnews/article/088/0001027574"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/066970/news"
  },
  "오르비텍": {
    "company": "오르비텍",
    "code": "046120",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=046120",
    "news": {
      "title": "미국 원전 건설 기대감에 원전주들 ‘불기둥’…오르비텍 상한가 기록...",
      "office": "매일경제",
      "date": "20260908",
      "url": "https://n.news.naver.com/mnews/article/009/0005731875"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/046120/news"
  },
  "오픈엣지테크놀로지": {
    "company": "오픈엣지테크놀로지",
    "code": "394280",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=394280",
    "news": {
      "title": "[이 시각 시황] 피지컬 AI·로봇주 강세…LG-엔비디아 협력 기대",
      "office": "SBS Biz",
      "date": "20260814",
      "url": "https://n.news.naver.com/mnews/article/374/0000527464"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/394280/news"
  },
  "올릭스": {
    "company": "올릭스",
    "code": "226950",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=226950",
    "news": {
      "title": "올릭스, 탈모약 호주 임상 1b상 추적관찰 완료…연내 2a상 진입 목표",
      "office": "이데일리",
      "date": "20260824",
      "url": "https://n.news.naver.com/mnews/article/018/0006357099"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/226950/news"
  },
  "우리기술": {
    "company": "우리기술",
    "code": "032820",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=032820",
    "news": {
      "title": "\"美 원전 짓는다\" 들썩…3일 만에 33% '불기둥' 뿜은 종목 [분석+]",
      "office": "한국경제",
      "date": "20260910",
      "url": "https://n.news.naver.com/mnews/article/015/0005330712"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/032820/news"
  },
  "우진": {
    "company": "우진",
    "code": "105840",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=105840",
    "news": {
      "title": "우진, 한국수력원자력과 109억 규모 공급계약 체결",
      "office": "헤럴드경제",
      "date": "20260617",
      "url": "https://n.news.naver.com/mnews/article/016/0002657906"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/105840/news"
  },
  "우진엔텍": {
    "company": "우진엔텍",
    "code": "457550",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=457550",
    "news": {
      "title": "우진엔텍, 원전 방사선감시계통 MI 케이블 어셈블리 국산화",
      "office": "뉴시스",
      "date": "20260714",
      "url": "https://n.news.naver.com/mnews/article/003/0014064540"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/457550/news"
  },
  "원익머트리얼즈": {
    "company": "원익머트리얼즈",
    "code": "104830",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=104830",
    "news": {
      "title": "“반도체용 특수가스 기업 원익머트리얼즈, 영업이익 올해 673억→ 내...",
      "office": "주간동아",
      "date": "20260821",
      "url": "https://n.news.naver.com/mnews/article/037/0000038708"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/104830/news"
  },
  "원익피앤이": {
    "company": "원익피앤이",
    "code": "217820",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=217820",
    "news": {
      "title": "원익피앤이·씨엘모빌리티, '충전 연동형 EV 플릿 통합관제' 공동 개발...",
      "office": "한경비즈니스",
      "date": "20260819",
      "url": "https://n.news.naver.com/mnews/article/050/0000109875"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/217820/news"
  },
  "원익IPS": {
    "company": "원익IPS",
    "code": "240810",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=240810",
    "news": {
      "title": "“3년물 4%·유가 100달러·환율 1345원…‘3高 트리플 쇼크’ 현실화...",
      "office": "서울경제",
      "date": "20260912",
      "url": "https://n.news.naver.com/mnews/article/011/0004661113"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/240810/news"
  },
  "유진테크": {
    "company": "유진테크",
    "code": "084370",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=084370",
    "news": {
      "title": "유진테크, 864억 규모 신규 시설 투자 결정",
      "office": "이데일리",
      "date": "20260909",
      "url": "https://n.news.naver.com/mnews/article/018/0006366292"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/084370/news"
  },
  "유한양행": {
    "company": "유한양행",
    "code": "000100",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=000100",
    "news": {
      "title": "유한양행 ‘렉라자’, 제1회 ‘프리 갈리앵 코리아’ 최우수 제약제품...",
      "office": "이코노미스트",
      "date": "20260911",
      "url": "https://n.news.naver.com/mnews/article/243/0000102938"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/000100/news"
  },
  "이노스페이스": {
    "company": "이노스페이스",
    "code": "462350",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=462350",
    "news": {
      "title": "이노스페이스, 경기국방벤처센터 하반기 협약기업 선정",
      "office": "파이낸셜뉴스",
      "date": "20260910",
      "url": "https://n.news.naver.com/mnews/article/014/0005573795"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/462350/news"
  },
  "이수페타시스": {
    "company": "이수페타시스",
    "code": "007660",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=007660",
    "news": {
      "title": "영풍전자, 빅테크에 고다층 MLB 공급...신사업 결실",
      "office": "지디넷코리아",
      "date": "20260911",
      "url": "https://n.news.naver.com/mnews/article/092/0002437157"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/007660/news"
  },
  "인텔리안테크": {
    "company": "인텔리안테크",
    "code": "189300",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=189300",
    "news": {
      "title": "인텔리안테크, 글로벌 국방용 안테나 첫 수주…409억 규모",
      "office": "블로터",
      "date": "20260911",
      "url": "https://n.news.naver.com/mnews/article/293/0000090362"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/189300/news"
  },
  "일진전기": {
    "company": "일진전기",
    "code": "103590",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=103590",
    "news": {
      "title": "AI 데이터센터 기대감에 전선·광통신·통신장비 '고공행진'",
      "office": "뉴시스",
      "date": "20260909",
      "url": "https://n.news.naver.com/mnews/article/003/0014178717"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/103590/news"
  },
  "제노코": {
    "company": "제노코",
    "code": "361390",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=361390",
    "news": {
      "title": "'CB 오버행 변수' 제노코, 하반기 실적 반등 앞두고 물량 부담",
      "office": "동행미디어 시대",
      "date": "20260818",
      "url": "https://n.news.naver.com/mnews/article/417/0001155587"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/361390/news"
  },
  "제주반도체": {
    "company": "제주반도체",
    "code": "080220",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=080220",
    "news": {
      "title": "금리 치솟을 땐 투자전략 달라야…‘고ROA’주, 16개 종목 리스트는? ...",
      "office": "헤럴드경제",
      "date": "20260902",
      "url": "https://n.news.naver.com/mnews/article/016/0002692037"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/080220/news"
  },
  "주성엔지니어링": {
    "company": "주성엔지니어링",
    "code": "036930",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=036930",
    "news": {
      "title": "“3년물 4%·유가 100달러·환율 1345원…‘3高 트리플 쇼크’ 현실화...",
      "office": "서울경제",
      "date": "20260912",
      "url": "https://n.news.naver.com/mnews/article/011/0004661113"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/036930/news"
  },
  "지씨셀": {
    "company": "지씨셀",
    "code": "144510",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=144510",
    "news": {
      "title": "지씨셀, 라플레와 면역세포치료 예후 예측 AI 개발 맞손",
      "office": "서울경제",
      "date": "20260723",
      "url": "https://n.news.naver.com/mnews/article/011/0004644331"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/144510/news"
  },
  "지엔씨에너지": {
    "company": "지엔씨에너지",
    "code": "119850",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=119850",
    "news": {
      "title": "지엔씨에너지, 469억 규모 발전기 공급계약",
      "office": "뉴시스",
      "date": "20260911",
      "url": "https://n.news.naver.com/mnews/article/003/0014184123"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/119850/news"
  },
  "천보": {
    "company": "천보",
    "code": "278280",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=278280",
    "news": {
      "title": "동화일렉트로·피지티·천보, '북미 배터리 순환형 공급망' 협력",
      "office": "뉴스1",
      "date": "20260210",
      "url": "https://n.news.naver.com/mnews/article/421/0008765379"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/278280/news"
  },
  "칩스앤미디어": {
    "company": "칩스앤미디어",
    "code": "094360",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=094360",
    "news": {
      "title": "칩스앤미디어, ASIL-B 인증 차량용 IP 출시",
      "office": "아시아경제",
      "date": "20260903",
      "url": "https://n.news.naver.com/mnews/article/277/0005811157"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/094360/news"
  },
  "컨텍": {
    "company": "컨텍",
    "code": "451760",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=451760",
    "news": {
      "title": "컨텍 자회사 TXSpace, '블루오리진'과 지상국 안테나 공급",
      "office": "파이낸셜뉴스",
      "date": "20260811",
      "url": "https://n.news.naver.com/mnews/article/014/0005560008"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/451760/news"
  },
  "켄코아에어로스페이스": {
    "company": "켄코아에어로스페이스",
    "code": "274090",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=274090",
    "news": {
      "title": "켄코아에어로스페이스, KAI와 10년 장기 공급계약 체결",
      "office": "이데일리",
      "date": "20260729",
      "url": "https://n.news.naver.com/mnews/article/018/0006339175"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/274090/news"
  },
  "코스모신소재": {
    "company": "코스모신소재",
    "code": "005070",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=005070",
    "news": {
      "title": "코스모신소재, 150억 규모 피노 지분 인수계약 체결",
      "office": "뉴시스",
      "date": "20260907",
      "url": "https://n.news.naver.com/mnews/article/003/0014173043"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/005070/news"
  },
  "큐렉소": {
    "company": "큐렉소",
    "code": "060280",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=060280",
    "news": {
      "title": "큐렉소·에스오에스랩, 수술·의료로봇 공간지능 솔루션 개발 MOU 체결",
      "office": "이데일리",
      "date": "20260826",
      "url": "https://n.news.naver.com/mnews/article/018/0006358187"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/060280/news"
  },
  "큐로셀": {
    "company": "큐로셀",
    "code": "372320",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=372320",
    "news": {
      "title": "큐로셀 국산 CAR-T 급여 ‘성큼’…유한양행 API 수주도 순항 [바이오...",
      "office": "이데일리",
      "date": "20260906",
      "url": "https://n.news.naver.com/mnews/article/018/0006364319"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/372320/news"
  },
  "클로봇": {
    "company": "클로봇",
    "code": "466100",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=466100",
    "news": {
      "title": "클로봇, DLS 인수 마무리…물류자동화 시너지 낸다",
      "office": "아이뉴스24",
      "date": "20260901",
      "url": "https://n.news.naver.com/mnews/article/031/0001054127"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/466100/news"
  },
  "태성": {
    "company": "태성",
    "code": "323280",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=323280",
    "news": {
      "title": "태성, 9월 수주 2200억원 돌파…\"지난해 연간 매출액 5.8배\"",
      "office": "아시아경제",
      "date": "20260904",
      "url": "https://n.news.naver.com/mnews/article/277/0005811825"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/323280/news"
  },
  "테스": {
    "company": "테스",
    "code": "095610",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=095610",
    "news": {
      "title": "\"테스, 수주잔고 폭발적 성장…투자의견 '매수'·목표가 21만원\"-IBK",
      "office": "머니투데이",
      "date": "20260910",
      "url": "https://n.news.naver.com/mnews/article/008/0005411784"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/095610/news"
  },
  "테크윙": {
    "company": "테크윙",
    "code": "089030",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=089030",
    "news": {
      "title": "K-반도체 메모리 핸들러…테크윙, 美 마이크론 말레이·인도 공급 확대",
      "office": "뉴스1",
      "date": "20260903",
      "url": "https://n.news.naver.com/mnews/article/421/0009147791"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/089030/news"
  },
  "텔레칩스": {
    "company": "텔레칩스",
    "code": "054450",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=054450",
    "news": {
      "title": "하나證 \"텔레칩스, 개발 용역이 키운 실적…해외 확장도 가속화 긍정...",
      "office": "파이낸셜뉴스",
      "date": "20260729",
      "url": "https://n.news.naver.com/mnews/article/014/0005554297"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/054450/news"
  },
  "툴젠": {
    "company": "툴젠",
    "code": "199800",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=199800",
    "news": {
      "title": "툴젠, 심혈관질환 유전자치료제 개발 속도…\"내년 美 임상 신청\"",
      "office": "이데일리",
      "date": "20260903",
      "url": "https://n.news.naver.com/mnews/article/018/0006363281"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/199800/news"
  },
  "티로보틱스": {
    "company": "티로보틱스",
    "code": "117730",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=117730",
    "news": {
      "title": "티로보틱스, 美 ESS 자동화 모듈 추가 수주…누적 190억 규모",
      "office": "머니투데이",
      "date": "20260901",
      "url": "https://n.news.naver.com/mnews/article/008/0005407828"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/117730/news"
  },
  "티씨케이": {
    "company": "티씨케이",
    "code": "064760",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=064760",
    "news": {
      "title": "티씨케이, 1분기 매출 954억…전년대비 22%↑",
      "office": "이데일리",
      "date": "20260428",
      "url": "https://n.news.naver.com/mnews/article/018/0006268306"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/064760/news"
  },
  "파마리서치": {
    "company": "파마리서치",
    "code": "214450",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=214450",
    "news": {
      "title": "파마리서치, 산부인과 전문의와 여성 건강 해법 모색…홈케어 제품군...",
      "office": "한국경제",
      "date": "20260911",
      "url": "https://n.news.naver.com/mnews/article/015/0005331389"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/214450/news"
  },
  "퍼스텍": {
    "company": "퍼스텍",
    "code": "010820",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=010820",
    "news": {
      "title": "종전 MOU에 재건주 '들썩'…퍼스텍 '上'·대우건설 24%↑",
      "office": "뉴시스",
      "date": "20260616",
      "url": "https://n.news.naver.com/mnews/article/003/0014008443"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/010820/news"
  },
  "펩트론": {
    "company": "펩트론",
    "code": "087010",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=087010",
    "news": {
      "title": "카카오헬스, 'AI 네이티브 EMR' 만든다…'메디테크' 사흘 대장정",
      "office": "머니투데이",
      "date": "20260909",
      "url": "https://n.news.naver.com/mnews/article/008/0005411658"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/087010/news"
  },
  "포스코퓨처엠": {
    "company": "포스코퓨처엠",
    "code": "003670",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=003670",
    "news": {
      "title": "[AI 대전환 리딩 전략] 포스코퓨처엠, AI 전력수요 LFP로 승부",
      "office": "블로터",
      "date": "20260909",
      "url": "https://n.news.naver.com/mnews/article/293/0000090234"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/003670/news"
  },
  "피에스케이": {
    "company": "피에스케이",
    "code": "319660",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=319660",
    "news": {
      "title": "반도체 장비주, 차익실현 매물에 약세…한미반도체 8%↓[핫종목]",
      "office": "뉴스1",
      "date": "20260911",
      "url": "https://n.news.naver.com/mnews/article/421/0009164476"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/319660/news"
  },
  "피엔티": {
    "company": "피엔티",
    "code": "137400",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=137400",
    "news": {
      "title": "미래에셋, 피엔티 목표가↓…\"3분기에는 영업이익 회복 전망\"",
      "office": "연합뉴스",
      "date": "20260901",
      "url": "https://n.news.naver.com/mnews/article/001/0016281422"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/137400/news"
  },
  "필옵틱스": {
    "company": "필옵틱스",
    "code": "161580",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=161580",
    "news": {
      "title": "2㎜ 두께 유리기판도 불량 ‘0’…필옵틱스, TGV 기술력 과시",
      "office": "서울경제",
      "date": "20260910",
      "url": "https://n.news.naver.com/mnews/article/011/0004660439"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/161580/news"
  },
  "하나마이크론": {
    "company": "하나마이크론",
    "code": "067310",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=067310",
    "news": {
      "title": "제너셈, 하나마이크론과 119억 규모 반도체 후공정 장비 계약",
      "office": "이데일리",
      "date": "20260907",
      "url": "https://n.news.naver.com/mnews/article/018/0006365000"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/067310/news"
  },
  "하나머티리얼즈": {
    "company": "하나머티리얼즈",
    "code": "166090",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=166090",
    "news": {
      "title": "하나머티리얼즈, 메모리 증설에 Si 파츠 수요↑…내년 실적 가속-SK",
      "office": "이데일리",
      "date": "20260903",
      "url": "https://n.news.naver.com/mnews/article/018/0006362809"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/166090/news"
  },
  "하이젠알앤엠": {
    "company": "하이젠알앤엠",
    "code": "160190",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=160190",
    "news": {
      "title": "하이젠알앤엠 9만원일 땐 외면하더니… 타이밍 놓친 만년 저평가주 일...",
      "office": "조선비즈",
      "date": "20260602",
      "url": "https://n.news.naver.com/mnews/article/366/0001168742"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/160190/news"
  },
  "하이즈항공": {
    "company": "하이즈항공",
    "code": "221840",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=221840",
    "news": {
      "title": "하이즈항공, 대한항공에 보잉 치누크 헬기 부품 공급…51억원 규모",
      "office": "동행미디어 시대",
      "date": "20260512",
      "url": "https://n.news.naver.com/mnews/article/417/0001142773"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/221840/news"
  },
  "한국항공우주": {
    "company": "한국항공우주",
    "code": "047810",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=047810",
    "news": {
      "title": "[인터뷰] 2000억 투입한 네이버, '보파모'로 사업보국 실현…\"AI 보안 ...",
      "office": "지디넷코리아",
      "date": "20260911",
      "url": "https://n.news.naver.com/mnews/article/092/0002437056"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/047810/news"
  },
  "한미반도체": {
    "company": "한미반도체",
    "code": "042700",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=042700",
    "news": {
      "title": "반도체 장비주, 차익실현 매물에 약세…한미반도체 8%↓[핫종목]",
      "office": "뉴스1",
      "date": "20260911",
      "url": "https://n.news.naver.com/mnews/article/421/0009164476"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/042700/news"
  },
  "한솔케미칼": {
    "company": "한솔케미칼",
    "code": "014680",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=014680",
    "news": {
      "title": "2차전지 상위 10사 법인세 529억…매출 줄어도 전년비 37%↑ [2026년 상...",
      "office": "조세일보",
      "date": "20260907",
      "url": "https://n.news.naver.com/mnews/article/123/0002389694"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/014680/news"
  },
  "한전기술": {
    "company": "한전기술",
    "code": "052690",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=052690",
    "news": {
      "title": "[애프터마켓 리뷰] 미 원전 건설 기대에 한전기술 등 원전주 급등",
      "office": "SBS Biz",
      "date": "20260909",
      "url": "https://n.news.naver.com/mnews/article/374/0000531911"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/052690/news"
  },
  "한전산업": {
    "company": "한전산업",
    "code": "130660",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=130660",
    "news": {
      "title": "한전산업, 광복절 맞아 독립유공자 후손 위한 ‘행복한 사진관’ 사회...",
      "office": "동아일보",
      "date": "20260715",
      "url": "https://n.news.naver.com/mnews/article/020/0003734062"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/130660/news"
  },
  "한전KPS": {
    "company": "한전KPS",
    "code": "051600",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=051600",
    "news": {
      "title": "한전KPS, 조선대서 '탄소중립·ESG' 프로그램 운영",
      "office": "연합뉴스",
      "date": "20260910",
      "url": "https://n.news.naver.com/mnews/article/001/0016302911"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/051600/news"
  },
  "한중엔시에스": {
    "company": "한중엔시에스",
    "code": "107640",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=107640",
    "news": {
      "title": "[한중엔시에스 줌인]② 美 투자에 현금소요 확대…800억 신종자본 선...",
      "office": "블로터",
      "date": "20260826",
      "url": "https://n.news.naver.com/mnews/article/293/0000089558"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/107640/news"
  },
  "한화에어로스페이스": {
    "company": "한화에어로스페이스",
    "code": "012450",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=012450",
    "news": {
      "title": "대기업 하반기 채용 본격화…\"AI 활용한 문제 해결 능력 중시\"[AI로 달...",
      "office": "뉴시스",
      "date": "20260912",
      "url": "https://n.news.naver.com/mnews/article/003/0014185903"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/012450/news"
  },
  "현대건설": {
    "company": "현대건설",
    "code": "000720",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=000720",
    "news": {
      "title": "살까 팔까 버틸까…기로에 선 부동산 투자, 여기 답있다",
      "office": "한국경제",
      "date": "20260911",
      "url": "https://n.news.naver.com/mnews/article/015/0005331426"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/000720/news"
  },
  "현대무벡스": {
    "company": "현대무벡스",
    "code": "319400",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=319400",
    "news": {
      "title": "[이 시각 시황] 피지컬 AI·로봇주 강세…LG-엔비디아 협력 기대",
      "office": "SBS Biz",
      "date": "20260814",
      "url": "https://n.news.naver.com/mnews/article/374/0000527464"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/319400/news"
  },
  "효성중공업": {
    "company": "효성중공업",
    "code": "298040",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=298040",
    "news": {
      "title": "효성중공업, 세계 최대 전력 전시회 참가…차세대 전력 설루션 선봬",
      "office": "뉴스1",
      "date": "20260825",
      "url": "https://n.news.naver.com/mnews/article/421/0009130615"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/298040/news"
  },
  "휴니드": {
    "company": "휴니드",
    "code": "005870",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=005870",
    "news": {
      "title": "휴니드, 한 달간 美 보잉향 공급계약 3건 수주",
      "office": "블로터",
      "date": "20260605",
      "url": "https://n.news.naver.com/mnews/article/293/0000085842"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/005870/news"
  },
  "휴젤": {
    "company": "휴젤",
    "code": "145020",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=145020",
    "news": {
      "title": "대웅·휴젤 나란히 1조…국산 톡신, 수출산업 됐다",
      "office": "동행미디어 시대",
      "date": "20260904",
      "url": "https://n.news.naver.com/mnews/article/417/0001157365"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/145020/news"
  },
  "AP위성": {
    "company": "AP위성",
    "code": "211270",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=211270",
    "news": {
      "title": "​AP위성, 8000억 규모 '백두체계' 데이터링크 모뎀 공급",
      "office": "블로터",
      "date": "20260824",
      "url": "https://n.news.naver.com/mnews/article/293/0000089448"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/211270/news"
  },
  "HD현대일렉트릭": {
    "company": "HD현대일렉트릭",
    "code": "267260",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=267260",
    "news": {
      "title": "\"AI 전력시장 뚫는다\" 정기선號 HD현대, 엔진·SMR로 '2030년 매출 100조...",
      "office": "뉴시스",
      "date": "20260911",
      "url": "https://n.news.naver.com/mnews/article/003/0014183539"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/267260/news"
  },
  "HK이노엔": {
    "company": "HK이노엔",
    "code": "195940",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=195940",
    "news": {
      "title": "HK이노엔, 매출 '1조 클럽' 이끈 국민 위장약 … 美시장도 뚫는다",
      "office": "매일경제",
      "date": "20260909",
      "url": "https://n.news.naver.com/mnews/article/009/0005732736"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/195940/news"
  },
  "HPSP": {
    "company": "HPSP",
    "code": "403870",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=403870",
    "news": {
      "title": "[서울데이터랩]마감 직후 인기 검색 종목 20選",
      "office": "서울신문",
      "date": "20260910",
      "url": "https://n.news.naver.com/mnews/article/081/0003679018"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/403870/news"
  },
  "ISC": {
    "company": "ISC",
    "code": "095340",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=095340",
    "news": {
      "title": "ISC, SK하이닉스향 테스트소켓 매출 14배↑…SK 편입 후 거래 확대",
      "office": "전자신문",
      "date": "20260830",
      "url": "https://n.news.naver.com/mnews/article/030/0003461610"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/095340/news"
  },
  "LG에너지솔루션": {
    "company": "LG에너지솔루션",
    "code": "373220",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=373220",
    "news": {
      "title": "중국 CXMT, 영업이익률 82%…SK하이닉스·삼성전자 제쳤다",
      "office": "서울경제",
      "date": "20260912",
      "url": "https://n.news.naver.com/mnews/article/011/0004661116"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/373220/news"
  },
  "LIG넥스원": {
    "company": "LIG넥스원",
    "code": "079550",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=079550",
    "news": {
      "title": "국방 AI, 기다리다 기회 놓친다…전력화 속도가 관건",
      "office": "지디넷코리아",
      "date": "20260909",
      "url": "https://n.news.naver.com/mnews/article/092/0002436815"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/079550/news"
  },
  "LS": {
    "company": "LS",
    "code": "006260",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=006260",
    "news": {
      "title": "LS전선, 5000억원 규모 교환사채 발행…북미 투자 [공시]",
      "office": "파이낸셜뉴스",
      "date": "20260911",
      "url": "https://n.news.naver.com/mnews/article/014/0005574602"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/006260/news"
  },
  "LS ELECTRIC": {
    "company": "LS ELECTRIC",
    "code": "010120",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=010120",
    "news": {
      "title": "HD현대중공업, 2030년 엔진 매출 10조원 전망…대우건설, 팀코리아 원...",
      "office": "파이낸셜뉴스",
      "date": "20260911",
      "url": "https://n.news.naver.com/mnews/article/014/0005574433"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/010120/news"
  },
  "LS마린솔루션": {
    "company": "LS마린솔루션",
    "code": "060370",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=060370",
    "news": {
      "title": "LS마린솔루션, 상반기 영업이익 전년比 61%↑…LS전선 3개 자회사 나란...",
      "office": "전자신문",
      "date": "20260904",
      "url": "https://n.news.naver.com/mnews/article/030/0003463495"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/060370/news"
  },
  "LS에코에너지": {
    "company": "LS에코에너지",
    "code": "229640",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=229640",
    "news": {
      "title": "LS에코에너지 6.32%·국순당 5.57% 상승…강원 상장사 희비",
      "office": "강원도민일보",
      "date": "20260909",
      "url": "https://n.news.naver.com/mnews/article/654/0000199668"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/229640/news"
  },
  "SK바이오사이언스": {
    "company": "SK바이오사이언스",
    "code": "302440",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=302440",
    "news": {
      "title": "빅파마-K제약 '판매 동맹' 확산…똘똘한 품목, 실적 바꾼다",
      "office": "비즈워치",
      "date": "20260909",
      "url": "https://n.news.naver.com/mnews/article/648/0000050613"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/302440/news"
  },
  "SK바이오팜": {
    "company": "SK바이오팜",
    "code": "326030",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=326030",
    "news": {
      "title": "[콘퍼런스콜] SK바이오팜, 오파칼림 독성 인지…계약 근거는 종특이성",
      "office": "블로터",
      "date": "20260912",
      "url": "https://n.news.naver.com/mnews/article/293/0000090370"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/326030/news"
  },
  "SK이노베이션": {
    "company": "SK이노베이션",
    "code": "096770",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=096770",
    "news": {
      "title": "파리서 'AI 동맹' 맺은 이재용·울산 간 최태원·1조 베팅 정기선 [재...",
      "office": "데일리안",
      "date": "20260912",
      "url": "https://n.news.naver.com/mnews/article/119/0003131875"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/096770/news"
  },
  "SK하이닉스": {
    "company": "SK하이닉스",
    "code": "000660",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=000660",
    "news": {
      "title": "\"자소서 대신 AI 활용 경험\"…SK하이닉스, 채용 방식 뒤집었다[AI로 달...",
      "office": "뉴시스",
      "date": "20260912",
      "url": "https://n.news.naver.com/mnews/article/003/0014185968"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/000660/news"
  },
  "SKC": {
    "company": "SKC",
    "code": "011790",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=011790",
    "news": {
      "title": "SKC 유리기판, 수율 안정화 단계로…\"첫 양산 인증이 핵심\" IBK투자증권",
      "office": "파이낸셜뉴스",
      "date": "20260910",
      "url": "https://n.news.naver.com/mnews/article/014/0005573650"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/011790/news"
  },
  "SNT에너지": {
    "company": "SNT에너지",
    "code": "100840",
    "updatedAt": "2026-08-27",
    "report": null,
    "reportListUrl": "https://finance.naver.com/research/company_list.naver?searchType=itemCode&itemCode=100840",
    "news": {
      "title": "SNT에너지, 하동 LNG복합발전소 HRSG 수주",
      "office": "파이낸셜뉴스",
      "date": "20260902",
      "url": "https://n.news.naver.com/mnews/article/014/0005570246"
    },
    "newsListUrl": "https://m.stock.naver.com/domestic/stock/100840/news"
  }
};
